# Generated by Django 5.2 on 2025-04-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_item_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-Kd9Zp0N-SoXmnvK-hNmOzWj7IDISfhGEszzYfSY0y8slKm67RC_MkLr7VePiUamSidE&usqp=CAU",
                max_length=500,
            ),
        ),
    ]
