# Generated by Django 5.2 on 2025-04-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://cdn.pixabay.com/photo/2021/04/06/15/00/pie-6156640_1280.jpg', max_length=500),
        ),
    ]
